sudo: required
dist: xenial
language: python

env:
  global:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

services:
  - docker

stages:
  - name: BUILD

jobs:
  include:
    - stage: BUILD
      script:
        - docker-compose build
      after_success:
        - echo "Python version [${TRAVIS_PYTHON_VERSION}]"
        - echo "Git commit [${TRAVIS_COMMIT}]"
        - docker tag svc-postgres rafaelbattesti/posterkata/postgres
        - docker login --username rafaelbattesti --password ${REGISTRY_TOKEN}
        - docker push rafaelbattesti/posterkata/postgres
        - docker logout
      after_failure:
        - echo "The build stage failed. Skipping deploy to CEDP."
