version: "3"
services:
  svc-postgres:
    image: svc-postgres
    restart: always
    container_name: svc-postgres
    build:
      context: .
      dockerfile: ./svc-postgres/Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: