version: "3"
services:

  py-base:
    image: py-base
    restart: always
    container_name: py-base
    build:
      context: .
      dockerfile: ./py-base/Dockerfile

  svc-postgres:
    image: svc-postgres
    restart: always
    container_name: svc-postgres
    build:
      context: .
      dockerfile: ./svc-postgres/Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  svc-datagen:
    image: svc-datagen
    restart: always
    container_name: svc-datagen
    build:
      context: .
      dockerfile: ./svc-datagen/Dockerfile

  svc-etl:
    image: svc-etl
    restart: always
    container_name: svc-etl
    build:
      context: .
      dockerfile: ./svc-etl/Dockerfile

  svc-etl-style:
    image: svc-etl-style
    container_name: svc-etl-style
    build:
      context: .
      dockerfile: ./svc-etl/test/style/Dockerfile

  svc-etl-pytest:
    image: svc-etl-pytest
    container_name: svc-etl-pytest
    build:
      context: .
      dockerfile: ./svc-etl/test/pytest/Dockerfile

volumes:
  pgdata: