version: "3"
services:

  py-base:
    image: py-base
    container_name: py-base
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build:
      context: .
      dockerfile: ./py-base/Dockerfile

  svc-postgres:
    image: svc-postgres
    restart: always
    container_name: svc-postgres
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build:
      context: .
      dockerfile: ./svc-postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  svc-datagen:
    image: svc-datagen
    container_name: svc-datagen
    build:
      context: .
      dockerfile: ./svc-datagen/Dockerfile
    depends_on:
      - py-base
      - svc-postgres

  svc-etl:
    image: svc-etl
    restart: always
    container_name: svc-etl
    build:
      context: .
      dockerfile: ./svc-etl/Dockerfile
    depends_on:
      - py-base
      - svc-postgres

  svc-etl-style:
    image: svc-etl-style
    container_name: svc-etl-style
    build:
      context: .
      dockerfile: ./svc-etl/test/style/Dockerfile
    depends_on:
      - svc-etl

  svc-etl-pytest:
    image: svc-etl-pytest
    container_name: svc-etl-pytest
    build:
      context: .
      dockerfile: ./svc-etl/test/pytest/Dockerfile
    depends_on:
      - svc-etl

volumes:
  pgdata: